/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Kobayashi
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuComanda = new javax.swing.JMenu();
        comandaConsultar = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        clienteConsultar = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuConsultar = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        sobreApp = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuComanda.setText("Comanda");

        comandaConsultar.setText("Consultar");
        menuComanda.add(comandaConsultar);

        jMenuBar1.add(menuComanda);

        menuCliente.setText("Cliente");

        clienteConsultar.setText("Consultar");
        clienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteConsultarActionPerformed(evt);
            }
        });
        menuCliente.add(clienteConsultar);

        jMenuBar1.add(menuCliente);

        menuProduto.setText("Produto");

        menuConsultar.setText("Consultar");
        menuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarActionPerformed(evt);
            }
        });
        menuProduto.add(menuConsultar);

        jMenuBar1.add(menuProduto);

        menuSobre.setText("Sobre");

        sobreApp.setText("Sobre o Aplicativo");
        menuSobre.add(sobreApp);

        jMenuBar1.add(menuSobre);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultarActionPerformed

    private void clienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteConsultarActionPerformed
        FrameCliente frameCliente = new FrameCliente();
        frameCliente.setVisible(true);
    }//GEN-LAST:event_clienteConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clienteConsultar;
    private javax.swing.JMenuItem comandaConsultar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuComanda;
    private javax.swing.JMenuItem menuConsultar;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem sobreApp;
    // End of variables declaration//GEN-END:variables
}
